name: RSS抓取定时任务

on:
  schedule:
    # 每天UTC时间02:00运行 (北京时间10:00)
    - cron: '0 2 * * *'
  workflow_dispatch: # 允许手动触发

jobs:
  crawl-rss:
    runs-on: ubuntu-latest
    
    steps:
    - name: 抓取制造业RSS源
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
      run: |
        echo "开始RSS抓取任务..."
        
        # RSS源配置
        sources='[
          {
            "rssUrl": "https://news.google.com/rss/search?q=manufacturing+factory+automation&hl=en-US&gl=US&ceid=US:en",
            "sourceName": "Google News - 制造业",
            "verticalName": "制造业"
          },
          {
            "rssUrl": "https://news.google.com/rss/search?q=industry+4.0+smart+manufacturing&hl=en-US&gl=US&ceid=US:en", 
            "sourceName": "Google News - 工业4.0",
            "verticalName": "制造业"
          },
          {
            "rssUrl": "https://www.themanufacturer.com/feed/",
            "sourceName": "The Manufacturer", 
            "verticalName": "制造业"
          },
          {
            "rssUrl": "https://www.manufacturing.net/rss.xml",
            "sourceName": "Manufacturing.net",
            "verticalName": "制造业"
          }
        ]'
        
        # 处理每个RSS源
        echo "$sources" | jq -c '.[]' | while read config; do
          echo "处理RSS源: $(echo "$config" | jq -r '.sourceName')"
          
          response=$(curl -s -X POST "${SUPABASE_URL}/functions/v1/fetch-rss" \
            -H "Authorization: Bearer ${SUPABASE_ANON_KEY}" \
            -H "Content-Type: application/json" \
            -d "$config")
          
          echo "结果: $response"
          
          # 等待3秒避免频繁请求
          sleep 3
        done
        
        echo "✅ RSS抓取任务完成"

    - name: 发送结果通知 (可选)
      if: always()
      run: |
        echo "可以在这里添加通知逻辑 (邮件、Slack等)"